# Generated by Django 4.1 on 2022-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='tipo',
            field=models.ManyToManyField(to='webdev.tipo'),
        ),
    ]
