# Generated by Django 4.1 on 2022-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0002_tipo_remove_utilizador_tipo_utilizador_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='project_manager',
            field=models.BooleanField(default=False),
        ),
    ]
