# Generated by Django 4.1 on 2022-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0003_utilizador_developer_utilizador_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='architect',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
